"""In-memory UnityPackage staging tree, independent of archive serialization."""

from __future__ import annotations

from dataclasses import dataclass, field
import hashlib
import re
import unicodedata
from typing import Any, Iterable


_GUID_RE = re.compile(r"^[0-9a-f]{32}$")
_META_GUID_RE = re.compile(rb"(?m)^guid:\s*([0-9a-fA-F]{32})\s*$")
# Conservative package-relative budgets, not a claim about every host project.
MAX_UNITY_COMPONENT_BYTES = 120
MAX_UNITY_PATH_BYTES = 240
_RESERVED_COMPONENT_RE = re.compile(r"^(?:CON|PRN|AUX|NUL|COM[1-9¹²³]|LPT[1-9¹²³])$", re.I)


def normalize_unity_path(path: str) -> str:
    value = str(path or "").replace("\\", "/")
    parts = value.split("/")
    if not value or "\x00" in value or value.startswith("/") or re.match(r"^[A-Za-z]:", value):
        raise ValueError(f"invalid Unity pathname: {path!r}")
    if parts[0] != "Assets" or any(part in {"", ".", ".."} for part in parts):
        raise ValueError(f"unsafe Unity pathname: {path!r}")
    for part in parts:
        if (any(ord(char) < 32 or char in '<>:"|?*' for char in part)
                or part.endswith((".", " "))
                or _RESERVED_COMPONENT_RE.fullmatch(part.split('.')[0])
                or len(part.encode('utf-8')) > MAX_UNITY_COMPONENT_BYTES):
            raise ValueError(f"nonportable Unity pathname: {path!r}")
    if len(value.encode('utf-8')) > MAX_UNITY_PATH_BYTES:
        raise ValueError(f"Unity pathname exceeds package-relative budget: {path!r}")
    return "/".join(parts)


def portable_path_key(path: str) -> str:
    """Compare portable destinations without rewriting the stored human label."""
    return unicodedata.normalize('NFC', normalize_unity_path(path)).casefold()


def normalize_guid(guid: str) -> str:
    value = str(guid or "").lower()
    if not _GUID_RE.fullmatch(value):
        raise ValueError(f"invalid Unity asset GUID: {guid!r}")
    return value


@dataclass(frozen=True)
class StagedUnityAsset:
    guid: str
    pathname: str
    asset_bytes: bytes
    meta_bytes: bytes
    preview_bytes: bytes | None = None
    asset_type: str = ""
    source_identity: dict[str, Any] = field(default_factory=dict)
    export_identity: dict[str, Any] = field(default_factory=dict)
    operation: str = "PRESERVE"
    strategy: str = "PRESERVE_VERBATIM"
    provenance: dict[str, Any] = field(default_factory=dict)
    warnings: tuple[str, ...] = ()

    def __post_init__(self) -> None:
        object.__setattr__(self, "guid", normalize_guid(self.guid))
        object.__setattr__(self, "pathname", normalize_unity_path(self.pathname))
        object.__setattr__(self, "asset_bytes", bytes(self.asset_bytes))
        object.__setattr__(self, "meta_bytes", bytes(self.meta_bytes))

    @property
    def content_hash(self) -> str:
        return hashlib.sha256(self.asset_bytes).hexdigest()

    @property
    def meta_hash(self) -> str:
        return hashlib.sha256(self.meta_bytes).hexdigest()


class StagingTree:
    """Validated logical package contents keyed by GUID and normalized pathname."""

    def __init__(self, entries: Iterable[StagedUnityAsset] = ()):
        self._by_guid: dict[str, StagedUnityAsset] = {}
        self._by_path: dict[str, StagedUnityAsset] = {}
        for entry in entries:
            self.add(entry)

    @property
    def entries(self) -> tuple[StagedUnityAsset, ...]:
        return tuple(self._by_guid[guid] for guid in sorted(self._by_guid))

    def add(self, entry: StagedUnityAsset) -> None:
        meta_guids = _META_GUID_RE.findall(entry.meta_bytes)
        if len(meta_guids) != 1 or meta_guids[0].decode("ascii").lower() != entry.guid:
            raise ValueError(f"asset.meta GUID mismatch: {entry.guid}")
        guid = entry.guid
        existing_guid = self._by_guid.get(guid)
        if existing_guid is not None:
            if existing_guid != entry:
                raise ValueError(f"GUID collision: {guid}")
            return
        path_key = portable_path_key(entry.pathname)
        existing_path = self._by_path.get(path_key)
        if existing_path is not None:
            if existing_path.guid == entry.guid:
                return
            raise ValueError(f"pathname collision: {entry.pathname}")
        self._by_guid[guid] = entry
        self._by_path[path_key] = entry

    def get(self, guid: str) -> StagedUnityAsset:
        return self._by_guid[normalize_guid(guid)]

    def __len__(self) -> int:
        return len(self._by_guid)


def stage_asset_plan(plan: Any, payload_provider: Any) -> StagingTree:
    """Materialize a validated AssetPlan through an explicit payload provider.

    The provider is responsible for obtaining source or generated bytes.  It
    cannot silently materialize DELETE entries, and plans containing failed
    validation or collisions are rejected before any entry is added.
    """
    if getattr(plan, "errors", ()):
        raise ValueError("cannot stage an asset plan with errors")
    if getattr(plan, "collisions", ()):
        raise ValueError("cannot stage an asset plan with collisions")
    tree = StagingTree()
    for item in getattr(plan, "assets", ()):
        operation = getattr(getattr(item, "operation", ""), "value", getattr(item, "operation", ""))
        if str(operation) == "DELETE":
            continue
        guid_decision = getattr(getattr(item, "guid_decision", ""), "value", getattr(item, "guid_decision", ""))
        if str(guid_decision) in {"AMBIGUOUS", "DEFER", "NOT_APPLICABLE", ""}:
            raise ValueError(f"asset plan has unresolved export identity: {getattr(item, 'node_id', '?')}")
        expected_guid = str(getattr(item, "export_identity", {}).get("export_guid", "") or "").lower()
        if not expected_guid and str(guid_decision) == "PRESERVE_SOURCE_GUID":
            expected_guid = str(getattr(item, "source_identity", {}).get("source_guid", "") or "").lower()
        expected_path = str(getattr(item, "desired_export_path", "") or "").replace("\\", "/")
        if not expected_path and str(operation) in {
            "PRESERVE", "MODIFY", "PRESERVE_EXTERNAL", "UNSUPPORTED_PRESERVED"
        }:
            expected_path = str(getattr(item, "source_identity", {}).get("source_path", "") or "").replace("\\", "/")
        entry = payload_provider(item)
        if not isinstance(entry, StagedUnityAsset):
            raise TypeError("payload provider must return StagedUnityAsset")
        if expected_guid and entry.guid != normalize_guid(expected_guid):
            raise ValueError(f"payload GUID does not match export plan: {getattr(item, 'node_id', '?')}")
        if expected_path and entry.pathname != normalize_unity_path(expected_path):
            raise ValueError(f"payload pathname does not match export plan: {getattr(item, 'node_id', '?')}")
        if not expected_guid or not expected_path:
            raise ValueError(f"asset plan has incomplete export identity: {getattr(item, 'node_id', '?')}")
        tree.add(entry)
    return tree
