# SPDX-License-Identifier: GPL-3.0-or-later
"""Optional capture adapter for the existing public direct confirmed Skin fixture.

The diagnostic CP UV is authored before the final editing checkpoint. It never
changes production export settings or the editing scene during export.
"""
import hashlib
import json
from pathlib import Path
import tarfile
import bpy
from .blender_geometry_abcd import observe
from .blender_hierarchy_snapshot import snapshot


def configure(mesh):
    marker=mesh.data.uv_layers.new(name='Diagnostic_CP_Transport')
    for loop in mesh.data.loops:
        marker.data[loop.index].uv=(loop.vertex_index+1,.375)
    mesh['_vapb_test_cp_channel']=len(mesh.data.uv_layers)-1
    for index,obj in enumerate(bpy.context.scene.objects): obj.name='Renamed diagnostic object %d'%index


def capture(root,mesh):
    binding=json.loads(mesh['_vapb_renderer_binding'])
    skin=json.loads(mesh['_vapb_skin_binding'])
    row=observe(mesh,mesh['_vapb_fbx_geometry_uid'],mesh['_vapb_test_cp_channel'],len(mesh.data.vertices))
    rig=next(m.object for m in mesh.modifiers if m.type=='ARMATURE')
    # Groups resolve through actual Bone handles to persistent realization IDs.
    group_ids={b.name:str(b['_vapb_fbx_bone_realization_id']) for b in rig.data.bones
               if b.get('_vapb_fbx_bone_realization_id')}
    for weights in row['skin_weights']:
        for w in weights: w['group']=group_ids[w['group']]
    result=dict(package_sha256=hashlib.sha256((root/'Source.unitypackage').read_bytes()).hexdigest(),
                renderer_binding=binding,skin_binding=skin,before=row,
                hierarchy=snapshot('',{}, {'FINISHED'}),
                material_ids=[dict(guid=str(s.material.get('unity_material_guid','')),slot=i)
                              for i,s in enumerate(mesh.material_slots)])
    (root/'BoundedBlender.json').write_text(json.dumps(result,indent=2),encoding='utf-8')


def finish(root,package,mesh):
    saved=json.loads((root/'BoundedBlender.json').read_text())
    assert saved['hierarchy']==snapshot('',{}, {'FINISHED'}),'SUCCESS_CHANGED_SOURCE_GRAPH'
    # Capture exact generated bytes/recipe from the production Output Package.
    assets={}
    with tarfile.open(package) as archive:
        for item in archive:
            if item.name.endswith('/pathname'):
                path=archive.extractfile(item).read().decode()
                member=archive.getmember(item.name.rsplit('/',1)[0]+'/asset')
                assets[path]=archive.extractfile(member).read()
    manifest=json.loads(assets['Assets/VAPBExport/manifest.json'])
    task,=manifest['reference_rebind_tasks']
    fbx_path,=[p for p in assets if p.endswith('.fbx') and p.startswith('Assets/VAPBExport/')]
    assert hashlib.sha256(assets[fbx_path]).hexdigest()==task['model_sha256']
    folder=root/'Generated';folder.mkdir(exist_ok=True)
    (folder/'D1.fbx').write_bytes(assets[fbx_path])
    (folder/'ControlPointManifest.json').write_text(json.dumps(dict(meshes=[dict(
        uv_channel=int(mesh['_vapb_test_cp_channel']))])))
    (root/'BoundedRecipe.json').write_text(json.dumps(dict(task=task,manifest=manifest,
        output_sha256=hashlib.sha256(package.read_bytes()).hexdigest()),indent=2),encoding='utf-8')
    # Same Mesh/rig/receipt, real staged-skin failure, exact semantic rollback.
    from types import SimpleNamespace
    from unittest.mock import patch
    from unitypackage_blender_importer.operators import export_unitypackage as exporter
    rig=next(m.object for m in mesh.modifiers if m.type=='ARMATURE')
    before=snapshot('',{}, {'FINISHED'})
    calls=[]
    def fail(**options):
        calls.append(1)
        assert all(len(p.vertices)==3 for o in bpy.context.selected_objects if o.type=='MESH' for p in o.data.polygons)
        raise RuntimeError('INJECTED_BOUNDED_EXPORT_FAILURE')
    proxy=SimpleNamespace(context=bpy.context,data=bpy.data,types=bpy.types,
        ops=SimpleNamespace(export_scene=SimpleNamespace(fbx=fail)))
    failure=root/'IntentionalFailure.fbx'
    with patch.object(exporter,'bpy',proxy):
        try:exporter._export_staged_skin(bpy.context,mesh,rig,failure,json.loads(mesh['_vapb_skin_binding']))
        except RuntimeError as exc:assert str(exc)=='INJECTED_BOUNDED_EXPORT_FAILURE'
        else:raise AssertionError('FAILURE_NOT_PROPAGATED')
    assert calls==[1] and not failure.exists() and snapshot('',{}, {'FINISHED'})==before
    (root/'BoundedPreservation.json').write_text(json.dumps(dict(source_unchanged=True,
        rollback=True,rename_save_reopen=True,realization_id=task['realization_id'],
        fbx_sha256=task['model_sha256'])))
