"""Synthetic Unity source-package -> actual Blender GUI operator -> output package.

Run Blender factory/background with --python-exit-code 1, then -- project_dir.
The project is generated by VapbRoundtripProbe.Prepare using public Unity APIs.
"""
from pathlib import Path
import json
import sys

import bpy

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))


def main():
    import unitypackage_blender_importer as addon
    root = Path(sys.argv[sys.argv.index('--') + 1])
    output = root / (sys.argv[sys.argv.index('--output') + 1] if '--output' in sys.argv else 'Output.unitypackage')
    if '--prepare-fbx' in sys.argv:
        bpy.ops.object.select_all(action='SELECT')
        bpy.ops.object.delete(use_global=False)
        bpy.ops.mesh.primitive_cube_add()
        bpy.context.object.name = 'SyntheticNativeModel'
        target = root / 'Assets/VapbRoundtrip/Input.fbx'
        target.parent.mkdir(parents=True, exist_ok=True)
        assert not target.exists()
        assert bpy.ops.export_scene.fbx(filepath=str(target), use_selection=True,
            object_types={'MESH'}, use_custom_props=True, bake_anim=False) == {'FINISHED'}
        print('ROUNDTRIP_INPUT_FBX_PASS')
        return
    addon.register()
    try:
        bpy.ops.object.select_all(action='SELECT')
        bpy.ops.object.delete(use_global=False)
        assert bpy.ops.import_scene.unitypackage(filepath=str(root / 'Source.unitypackage'),
            import_mode='RECONSTRUCT', keep_extracted=False,
            source_storage_directory=str(root / 'BlenderSources')) == {'FINISHED'}
        roots = [o for o in bpy.context.scene.objects if o.get('_vapb_renderer_occurrences')]
        assert len(roots) == 1
        records = json.loads(roots[0]['_vapb_renderer_occurrences'])['records']
        assert len(records) == 1 and records[0]['renderer_class_id'] == 23
        native = [o for o in bpy.context.scene.objects if o.type == 'MESH'
            and o.get('_vapb_root_context_id') == records[0]['root_context_id']]
        assert len(native) == 1
        mesh = native[0]
        mesh.data = mesh.data.copy()
        bpy.context.scene.vapb_renderer_root = roots[0]
        bpy.context.scene.vapb_renderer_mesh = mesh
        assert bpy.ops.vapb.confirm_renderer_binding(occurrence_id=records[0]['occurrence_id']) == {'FINISHED'}
        mesh.name = 'Renamed edited occurrence'
        for vertex in mesh.data.vertices:
            vertex.co *= 1.25
        before = [tuple(v.co) for v in mesh.data.vertices]
        scene_count = len(bpy.data.scenes)
        object_count = len(bpy.data.objects)
        for obj in bpy.context.selected_objects:
            obj.select_set(False)
        mesh.select_set(True)
        bpy.context.view_layer.objects.active = mesh
        bpy.ops.wm.save_as_mainfile(filepath=str(root / 'Roundtrip.blend'))
        bpy.ops.wm.open_mainfile(filepath=str(root / 'Roundtrip.blend'))
        assert bpy.context.active_object.get('_vapb_renderer_binding')
        assert bpy.ops.export_scene.vapb_unitypackage(filepath=str(output)) == {'FINISHED'}
        assert len(bpy.data.scenes) == scene_count and len(bpy.data.objects) == object_count
        assert [tuple(v.co) for v in bpy.context.active_object.data.vertices] == before
        assert output.is_file()
        print('BLENDER_PACKAGE_ROUNDTRIP_PASS rename=1 reload=1 scene_unchanged=1 operator=1')
    finally:
        addon.unregister()


if __name__ == '__main__':
    main()
