"""Generic public-repository safety checks without product-specific deny lists."""

from __future__ import annotations

import hashlib
from pathlib import Path
import re
import subprocess
import unittest


ROOT = Path(__file__).resolve().parents[1]
TEXT_SUFFIXES = {
    ".py", ".md", ".json", ".yaml", ".yml", ".toml", ".txt", ".ps1",
    ".bat", ".cmd", ".sh", ".ini", ".cfg", ".log", ".csv", ".cs",
}
FORBIDDEN_BINARY_SUFFIXES = {".unitypackage", ".fbx", ".blend", ".psd", ".tga"}
PUBLIC_SYNTHETIC_ASSETS = {
    "tests/unity_alias_oracle/Assets/Oracle/Model.fbx":
        "7123dad66d3a4c0ec138a33363f9e6a315ad76a020a9206b949d2b1db3a9501a",
    # First-party Blender cube generated by the public roundtrip source probe.
    "tests/unity_final_state_probe/Assets/VapbFinalState/Input.fbx":
        "033cbbfebf5afa8ad531b9ed6a87799e0827a36024c11b6aeffb145f32cc6031",
    # First-party synthetic package; provenance and exact hash in REPRODUCTION.md.
    "tests/unity_model_material_probe/fixtures/ThreeSlotSource.unitypackage":
        "d6245d25c3cbd513c49b8d2e241b313a752331cd338563becab6eb7c819bfa0c",
}
LOCAL_PATH_PATTERNS = (
    re.compile(r"[A-Za-z]:" + re.escape("\\") + "Users" + re.escape("\\") + r"[^\\\r\n\"'`]+"),
    re.compile(re.escape("/") + "Users" + re.escape("/") + r"[^/\r\n\"'`]+"),
    re.compile(re.escape("/") + "home" + re.escape("/") + r"[^/\r\n\"'`]+"),
)
SECRET_PATTERNS = (
    re.compile(r"-----BEGIN [A-Z ]*PRIVATE KEY-----"),
    re.compile(r"\b(?:ghp_|github_pat_|xoxb-|xoxp-|sk-)[A-Za-z0-9_-]{16,}"),
    re.compile(r"\bBearer\s+[A-Za-z0-9._-]{20,}"),
)


def tracked_files() -> list[Path]:
    output = subprocess.check_output(["git", "ls-files"], cwd=ROOT, text=True)
    return [ROOT / line for line in output.splitlines() if line]


class PublicRepositoryHygieneTests(unittest.TestCase):
    def test_no_developer_paths_or_obvious_secrets_in_tracked_text(self):
        for path in tracked_files():
            if path.suffix.lower() not in TEXT_SUFFIXES:
                continue
            text = path.read_text(encoding="utf-8", errors="replace")
            for pattern in LOCAL_PATH_PATTERNS + SECRET_PATTERNS:
                self.assertIsNone(pattern.search(text), str(path))

    def test_no_proprietary_asset_binaries_are_tracked(self):
        tracked = tracked_files()
        offenders = [
            path.relative_to(ROOT).as_posix()
            for path in tracked
            if path.suffix.lower() in FORBIDDEN_BINARY_SUFFIXES
            and path.relative_to(ROOT).as_posix() not in PUBLIC_SYNTHETIC_ASSETS
        ]
        self.assertEqual(offenders, [])
        for relative, expected_sha in PUBLIC_SYNTHETIC_ASSETS.items():
            path = ROOT / relative
            if path in tracked:
                self.assertEqual(expected_sha, hashlib.sha256(path.read_bytes()).hexdigest())

    def test_real_package_probe_is_explicitly_local_only(self):
        probe = (ROOT / "tests" / "blender_real_identity_verify.py").read_text(encoding="utf-8")
        self.assertIn("UNITYPACKAGE_REAL_TEST_FILE", probe)
        self.assertIn("REAL_PACKAGE_TEST_SKIPPED", probe)


if __name__ == "__main__":
    unittest.main()
