"""Distribution ZIP completeness and import-graph checks."""

from __future__ import annotations

import sys
from pathlib import Path
import tempfile
import unittest
import zipfile

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from tools.build_distribution_zip import git_files, validate_zip  # noqa: E402


class DistributionZipTests(unittest.TestCase):
    def test_source_runtime_set_contains_preferences(self):
        members = git_files(ROOT, "HEAD")
        self.assertIn("preferences.py", members)
        self.assertIn("operators/import_unitypackage.py", members)
        self.assertIn("blender/roundtrip_export.py", members)
        self.assertIn("operators/texture_editing.py", members)
        self.assertIn("ui/texture_panel.py", members)

    def test_generated_zip_has_complete_runtime_set(self):
        archive_path = Path(__import__("os").environ["VAPB_DISTRIBUTION_ZIP"])
        if not archive_path.exists():
            self.skipTest("distribution ZIP is generated by the release/verification step")
        members = git_files(ROOT, "HEAD")
        validate_zip(archive_path, members)
        with zipfile.ZipFile(archive_path) as archive:
            self.assertIn("unitypackage_blender_importer/preferences.py", archive.namelist())


if __name__ == "__main__":
    unittest.main()
