using System;
using System.Collections.Generic;
using System.IO;
using UnityEditor;
using UnityEngine;

/// <summary>
/// Restores original Unity Material assets onto an FBX using the sidecar
/// generated by the Blender exporter. This is intentionally a manual tool:
/// it never edits or recreates the original .mat asset.
/// </summary>
public static class UnityPackageBlenderMaterialRestore
{
    private const int SupportedSchemaVersion = 1;
    private const string ManifestType = "unitypackage_blender_material_map";
    private const string RestoreMenu = "Tools/UnityPackage Blender/Restore Selected FBX Material Map";
    private const string RestoreFileMenu = "Tools/UnityPackage Blender/Restore FBX Material Map...";

    [Serializable]
    private sealed class Manifest
    {
        public int schema_version;
        public string manifest_type;
        public MaterialRecord[] materials;
        public BindingRecord[] bindings;
    }

    [Serializable]
    private sealed class MaterialRecord
    {
        public string material_key;
        public string exported_material_identifier;
        public string exported_material_name;
        public string unity_material_guid;
        public string unity_material_path;
        public string unity_material_name;
        public string unity_shader_guid;
        public string unity_shader_name;
    }

    [Serializable]
    private sealed class BindingRecord
    {
        public string object_name;
        public string object_path;
        public string renderer_type;
        public int material_slot_index;
        public string material_key;
        public string status;
    }

    [MenuItem(RestoreMenu)]
    private static void RestoreSelected()
    {
        string assetPath = AssetDatabase.GetAssetPath(Selection.activeObject);
        RestoreAtPath(assetPath);
    }

    [MenuItem(RestoreMenu, true)]
    private static bool ValidateRestoreSelected()
    {
        string assetPath = AssetDatabase.GetAssetPath(Selection.activeObject);
        return IsFbxAssetPath(assetPath);
    }

    [MenuItem(RestoreFileMenu)]
    private static void RestoreFromFile()
    {
        string absolutePath = EditorUtility.OpenFilePanel("Select exported FBX", Application.dataPath, "fbx");
        if (string.IsNullOrEmpty(absolutePath))
            return;
        string assetPath = FileUtil.GetProjectRelativePath(absolutePath).Replace('\\', '/');
        RestoreAtPath(assetPath);
    }

    /// <summary>Restore one project-local FBX. Returns false for invalid or unresolved input.</summary>
    public static bool RestoreAtPath(string fbxAssetPath)
    {
        fbxAssetPath = NormalizeAssetPath(fbxAssetPath);
        if (!IsFbxAssetPath(fbxAssetPath))
        {
            Debug.LogError("Material restore requires a project-local .fbx asset: " + fbxAssetPath);
            return false;
        }

        string manifestAssetPath = GetManifestAssetPath(fbxAssetPath);
        string manifestDiskPath = ProjectAssetToDiskPath(manifestAssetPath);
        if (!File.Exists(manifestDiskPath))
        {
            Debug.LogError("Material map not found: " + manifestAssetPath);
            return false;
        }

        Manifest manifest;
        try
        {
            manifest = JsonUtility.FromJson<Manifest>(File.ReadAllText(manifestDiskPath));
        }
        catch (Exception exception)
        {
            Debug.LogError("Material map JSON is invalid: " + exception.Message);
            return false;
        }

        if (!ValidateManifest(manifest))
            return false;

        AssetImporter importer = AssetImporter.GetAtPath(fbxAssetPath);
        if (importer == null)
        {
            Debug.LogError("No AssetImporter exists for: " + fbxAssetPath);
            return false;
        }
        if (!importer.SupportsRemappedAssetType(typeof(Material)))
        {
            Debug.LogError("This importer does not support Material remapping: " + fbxAssetPath);
            return false;
        }

        var exportedNames = new HashSet<string>(StringComparer.Ordinal);
        int resolved = 0;
        int unresolved = 0;
        foreach (MaterialRecord record in manifest.materials)
        {
            string exportedName = record.exported_material_identifier;
            if (string.IsNullOrWhiteSpace(exportedName))
            {
                Debug.LogWarning("Material map entry has no exported material name: " + record.material_key);
                unresolved++;
                continue;
            }
            if (!exportedNames.Add(exportedName))
            {
                Debug.LogWarning("Duplicate exported material identifier; skipped: " + exportedName);
                unresolved++;
                continue;
            }

            Material original = ResolveOriginalMaterial(record);
            if (original == null)
            {
                unresolved++;
                continue;
            }

            try
            {
                importer.AddRemap(
                    new AssetImporter.SourceAssetIdentifier(typeof(Material), exportedName),
                    original);
                resolved++;
            }
            catch (Exception exception)
            {
                unresolved++;
                Debug.LogWarning("Could not remap '" + exportedName + "': " + exception.Message);
            }
        }

        if (resolved > 0)
        {
            // SaveAndReimport is the supported operation that writes importer
            // metadata and applies AddRemap to the imported model.
            importer.SaveAndReimport();
        }

        Debug.Log(
            "UnityPackage Blender Material Restore: " + fbxAssetPath
            + " resolved=" + resolved + " unresolved=" + unresolved);
        return unresolved == 0 && resolved > 0;
    }

    private static bool ValidateManifest(Manifest manifest)
    {
        if (manifest == null)
        {
            Debug.LogError("Material map is empty or invalid.");
            return false;
        }
        if (manifest.schema_version != SupportedSchemaVersion)
        {
            Debug.LogError("Unsupported material map schema_version: " + manifest.schema_version);
            return false;
        }
        if (!string.Equals(manifest.manifest_type, ManifestType, StringComparison.Ordinal))
        {
            Debug.LogError("Unsupported material map manifest_type: " + manifest.manifest_type);
            return false;
        }
        if (manifest.materials == null || manifest.bindings == null)
        {
            Debug.LogError("Material map must contain materials and bindings arrays.");
            return false;
        }

        var keys = new HashSet<string>(StringComparer.Ordinal);
        foreach (MaterialRecord record in manifest.materials)
        {
            if (record == null || string.IsNullOrWhiteSpace(record.material_key))
            {
                Debug.LogError("Material map contains a material without material_key.");
                return false;
            }
            if (!keys.Add(record.material_key))
            {
                Debug.LogError("Material map contains duplicate material_key: " + record.material_key);
                return false;
            }
        }

        foreach (BindingRecord binding in manifest.bindings)
        {
            if (binding == null)
            {
                Debug.LogError("Material map contains a null binding.");
                return false;
            }
            if (binding.status == "empty_slot")
                continue;
            if (string.IsNullOrWhiteSpace(binding.material_key) || !keys.Contains(binding.material_key))
            {
                Debug.LogError("Material map binding references an unknown material_key.");
                return false;
            }
            if (binding.material_slot_index < 0)
            {
                Debug.LogError("Material map contains a negative material slot index.");
                return false;
            }
        }
        return true;
    }

    private static Material ResolveOriginalMaterial(MaterialRecord record)
    {
        string guid = record.unity_material_guid ?? string.Empty;
        if (!string.IsNullOrWhiteSpace(guid))
        {
            string path = AssetDatabase.GUIDToAssetPath(guid);
            if (!string.IsNullOrEmpty(path))
            {
                Material material = AssetDatabase.LoadAssetAtPath<Material>(path);
                if (material != null)
                    return material;
                Debug.LogWarning("GUID does not resolve to a Material: " + guid + " at " + path);
            }
            else
            {
                Debug.LogWarning("Original material GUID not found: " + guid);
            }
        }

        string materialPath = NormalizeAssetPath(record.unity_material_path);
        if (IsProjectAssetPath(materialPath))
        {
            Material material = AssetDatabase.LoadAssetAtPath<Material>(materialPath);
            if (material != null)
                return material;
            if (!string.IsNullOrEmpty(materialPath))
                Debug.LogWarning("Original material path is not a Material: " + materialPath);
        }

        string name = record.unity_material_name ?? string.Empty;
        if (string.IsNullOrWhiteSpace(name))
        {
            Debug.LogWarning("Original material not found; no name fallback. GUID=" + guid + " Path=" + materialPath);
            return null;
        }

        var candidates = new List<Material>();
        foreach (string candidateGuid in AssetDatabase.FindAssets("t:Material"))
        {
            string candidatePath = AssetDatabase.GUIDToAssetPath(candidateGuid);
            Material candidate = AssetDatabase.LoadAssetAtPath<Material>(candidatePath);
            if (candidate != null && string.Equals(candidate.name, name, StringComparison.Ordinal))
                candidates.Add(candidate);
        }
        if (candidates.Count == 1)
            return candidates[0];
        if (candidates.Count > 1)
        {
            Debug.LogWarning("Ambiguous material name; left unresolved: " + name + " (" + candidates.Count + " matches)");
            return null;
        }

        Debug.LogWarning("Original material not found. GUID=" + guid + " Path=" + materialPath + " Name=" + name);
        return null;
    }

    private static bool IsFbxAssetPath(string path)
    {
        return IsProjectAssetPath(path) && string.Equals(Path.GetExtension(path), ".fbx", StringComparison.OrdinalIgnoreCase);
    }

    private static bool IsProjectAssetPath(string path)
    {
        return !string.IsNullOrEmpty(path)
            && (string.Equals(path, "Assets", StringComparison.OrdinalIgnoreCase)
                || path.StartsWith("Assets/", StringComparison.OrdinalIgnoreCase))
            && !path.Contains("..", StringComparison.Ordinal);
    }

    private static string NormalizeAssetPath(string path)
    {
        return (path ?? string.Empty).Replace('\\', '/').Trim();
    }

    private static string GetManifestAssetPath(string fbxAssetPath)
    {
        string directory = Path.GetDirectoryName(fbxAssetPath) ?? "Assets";
        string stem = Path.GetFileNameWithoutExtension(fbxAssetPath);
        return (directory + "/" + stem + ".materialmap.json").Replace('\\', '/');
    }

    private static string ProjectAssetToDiskPath(string assetPath)
    {
        string relative = assetPath.Substring("Assets".Length).TrimStart('/', '\\');
        return Path.Combine(Application.dataPath, relative);
    }

}
